// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	"amadeus-go/pkg/endpoint"

	"github.com/go-kit/kit/transport/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeHealthCheckHandler(m, endpoints, options["HealthCheck"])
	makeSearchHandler(m, endpoints, options["Search"])
	makeReserveFlightHandler(m, endpoints, options["AirBook"])
	makeAirBookHandler(m, endpoints, options["AirBookingData"])
	makeCancelPNRHandler(m, endpoints, options["CancelPNR"])
	makeAirRevalidateHandler(m, endpoints, options["AirRevalidate"])
	makeAirRulesHandler(m, endpoints, options["AirRules"])
	
	/* makeReserveTracingHandler(m, endpoints, options["ReserveTracing"])
	   makeCancelSeatHandler(m, endpoints, options["CancelSeat"])
	   makeETRefundHandler(m, endpoints, options["ETRefund"])
	   makeETRHandler(m, endpoints, options["ETR"])*/
	return m
}