// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iranairtour.proto

package search_struct

import (
	"context"
	"fmt"
	"math"

	"amadeus-go/pkg/transport/grpc/pb/types"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("iranairtour.proto", fileDescriptor_0ece43af73833a9e) }

var fileDescriptor_0ece43af73833a9e = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x37, 0x88, 0x82, 0x51, 0x11, 0x8c, 0x58, 0x40, 0x0a, 0x2a, 0x70, 0x80, 0x20, 0xc1,
	0x09, 0x42, 0x11, 0x74, 0x01, 0x08, 0x25, 0x12, 0xfb, 0x21, 0x8c, 0x1a, 0xab, 0x21, 0x0e, 0x33,
	0x4e, 0x51, 0xef, 0xc3, 0x41, 0x91, 0x9b, 0x98, 0x12, 0x9a, 0x76, 0xfb, 0xff, 0xfb, 0x2f, 0xb1,
	0x6c, 0x75, 0xa8, 0x19, 0x0b, 0xd4, 0x6c, 0x4d, 0xc5, 0x61, 0xc9, 0xc6, 0x1a, 0xe8, 0x0b, 0x21,
	0xa7, 0x59, 0x28, 0x96, 0xab, 0xd4, 0x06, 0x47, 0x76, 0x5e, 0x92, 0x5c, 0x7d, 0x90, 0x08, 0x4e,
	0x48, 0x6a, 0xe8, 0xfa, 0x7b, 0x4b, 0xf5, 0x12, 0xe2, 0x99, 0x4e, 0x09, 0x9e, 0xd4, 0xde, 0x98,
	0x30, 0xb7, 0xd9, 0x28, 0xa3, 0x74, 0x0a, 0xc3, 0xb0, 0x11, 0xb8, 0x61, 0xf8, 0xa7, 0x89, 0xe9,
	0xb3, 0x22, 0xb1, 0xc1, 0xd9, 0x7a, 0xa0, 0xcc, 0xe7, 0x30, 0x56, 0x07, 0x91, 0xe6, 0x47, 0xf3,
	0x75, 0x8f, 0x4c, 0xc9, 0x82, 0x84, 0xa0, 0x35, 0xa9, 0x43, 0xaf, 0x3b, 0xee, 0xec, 0x9c, 0x29,
	0x52, 0xbd, 0x48, 0xf3, 0xad, 0x31, 0x53, 0x18, 0xb4, 0xa0, 0x26, 0xf5, 0x86, 0x93, 0xee, 0xd2,
	0x29, 0x1e, 0xd4, 0xee, 0x08, 0x8b, 0x94, 0xf2, 0x97, 0xe7, 0x18, 0xda, 0x3f, 0xfe, 0x9b, 0x7b,
	0xcd, 0x60, 0x5d, 0xed, 0x44, 0xaf, 0x6a, 0xbf, 0x11, 0xeb, 0x62, 0x72, 0x87, 0x16, 0xe1, 0xb2,
	0xeb, 0xab, 0x4d, 0xe9, 0x95, 0xe7, 0x1b, 0x19, 0xe7, 0x4d, 0x54, 0x3f, 0xd2, 0x1c, 0xd3, 0x0c,
	0x73, 0xfd, 0x8e, 0x96, 0xe0, 0xe2, 0xff, 0x64, 0xd9, 0x79, 0xeb, 0x70, 0x13, 0x52, 0x9f, 0x7a,
	0xc7, 0xa5, 0x55, 0x4e, 0x02, 0xa7, 0x2b, 0xb0, 0x8b, 0xbb, 0xef, 0x72, 0xd9, 0x4a, 0x69, 0x0a,
	0xa1, 0xb7, 0xed, 0xc5, 0x6b, 0xb9, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x04, 0xe1, 0xc7, 0x90,
	0x67, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	HealthCheck(ctx context.Context, in *search_type.HealthCheckRequest, opts ...grpc.CallOption) (*search_type.HealthCheckReply, error)
	AirLowFareSearch(ctx context.Context, in *search_type.SearchRequest, opts ...grpc.CallOption) (*search_type.SearchReply, error)
	AirBook(ctx context.Context, in *search_type.AirBookRequest, opts ...grpc.CallOption) (*search_type.AirBookReply, error)
	CancelPNR(ctx context.Context, in *search_type.CancelPNRRequest, opts ...grpc.CallOption) (*search_type.CancelPNRReply, error)
	AirBookingData(ctx context.Context, in *search_type.AirBookingDataRequest, opts ...grpc.CallOption) (*search_type.AirBookingDataReply, error)
	AirRevalidate(ctx context.Context, in *search_type.AirRevalidateRequest, opts ...grpc.CallOption) (*search_type.AirRevalidateReply, error)
	AirRules(ctx context.Context, in *search_type.AirRulesRequest, opts ...grpc.CallOption) (*search_type.AirRulesResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) HealthCheck(ctx context.Context, in *search_type.HealthCheckRequest, opts ...grpc.CallOption) (*search_type.HealthCheckReply, error) {
	out := new(search_type.HealthCheckReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AirLowFareSearch(ctx context.Context, in *search_type.SearchRequest, opts ...grpc.CallOption) (*search_type.SearchReply, error) {
	out := new(search_type.SearchReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/AirLowFareSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AirBook(ctx context.Context, in *search_type.AirBookRequest, opts ...grpc.CallOption) (*search_type.AirBookReply, error) {
	out := new(search_type.AirBookReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/AirBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CancelPNR(ctx context.Context, in *search_type.CancelPNRRequest, opts ...grpc.CallOption) (*search_type.CancelPNRReply, error) {
	out := new(search_type.CancelPNRReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/CancelPNR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AirBookingData(ctx context.Context, in *search_type.AirBookingDataRequest, opts ...grpc.CallOption) (*search_type.AirBookingDataReply, error) {
	out := new(search_type.AirBookingDataReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/AirBookingData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AirRevalidate(ctx context.Context, in *search_type.AirRevalidateRequest, opts ...grpc.CallOption) (*search_type.AirRevalidateReply, error) {
	out := new(search_type.AirRevalidateReply)
	err := c.cc.Invoke(ctx, "/search.struct.Service/AirRevalidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AirRules(ctx context.Context, in *search_type.AirRulesRequest, opts ...grpc.CallOption) (*search_type.AirRulesResponse, error) {
	out := new(search_type.AirRulesResponse)
	err := c.cc.Invoke(ctx, "/search.struct.Service/AirRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	HealthCheck(context.Context, *search_type.HealthCheckRequest) (*search_type.HealthCheckReply, error)
	AirLowFareSearch(context.Context, *search_type.SearchRequest) (*search_type.SearchReply, error)
	AirBook(context.Context, *search_type.AirBookRequest) (*search_type.AirBookReply, error)
	CancelPNR(context.Context, *search_type.CancelPNRRequest) (*search_type.CancelPNRReply, error)
	AirBookingData(context.Context, *search_type.AirBookingDataRequest) (*search_type.AirBookingDataReply, error)
	AirRevalidate(context.Context, *search_type.AirRevalidateRequest) (*search_type.AirRevalidateReply, error)
	AirRules(context.Context, *search_type.AirRulesRequest) (*search_type.AirRulesResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) HealthCheck(ctx context.Context, req *search_type.HealthCheckRequest) (*search_type.HealthCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedServiceServer) AirLowFareSearch(ctx context.Context, req *search_type.SearchRequest) (*search_type.SearchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirLowFareSearch not implemented")
}
func (*UnimplementedServiceServer) AirBook(ctx context.Context, req *search_type.AirBookRequest) (*search_type.AirBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirBook not implemented")
}
func (*UnimplementedServiceServer) CancelPNR(ctx context.Context, req *search_type.CancelPNRRequest) (*search_type.CancelPNRReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPNR not implemented")
}
func (*UnimplementedServiceServer) AirBookingData(ctx context.Context, req *search_type.AirBookingDataRequest) (*search_type.AirBookingDataReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirBookingData not implemented")
}
func (*UnimplementedServiceServer) AirRevalidate(ctx context.Context, req *search_type.AirRevalidateRequest) (*search_type.AirRevalidateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirRevalidate not implemented")
}
func (*UnimplementedServiceServer) AirRules(ctx context.Context, req *search_type.AirRulesRequest) (*search_type.AirRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AirRules not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).HealthCheck(ctx, req.(*search_type.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AirLowFareSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AirLowFareSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/AirLowFareSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AirLowFareSearch(ctx, req.(*search_type.SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AirBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.AirBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AirBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/AirBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AirBook(ctx, req.(*search_type.AirBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CancelPNR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.CancelPNRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CancelPNR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/CancelPNR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CancelPNR(ctx, req.(*search_type.CancelPNRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AirBookingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.AirBookingDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AirBookingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/AirBookingData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AirBookingData(ctx, req.(*search_type.AirBookingDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AirRevalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.AirRevalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AirRevalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/AirRevalidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AirRevalidate(ctx, req.(*search_type.AirRevalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AirRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search_type.AirRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AirRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.struct.Service/AirRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AirRules(ctx, req.(*search_type.AirRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.struct.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Service_HealthCheck_Handler,
		},
		{
			MethodName: "AirLowFareSearch",
			Handler:    _Service_AirLowFareSearch_Handler,
		},
		{
			MethodName: "AirBook",
			Handler:    _Service_AirBook_Handler,
		},
		{
			MethodName: "CancelPNR",
			Handler:    _Service_CancelPNR_Handler,
		},
		{
			MethodName: "AirBookingData",
			Handler:    _Service_AirBookingData_Handler,
		},
		{
			MethodName: "AirRevalidate",
			Handler:    _Service_AirRevalidate_Handler,
		},
		{
			MethodName: "AirRules",
			Handler:    _Service_AirRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iranairtour.proto",
}